DEFS            +=      -DVERB
DEFS            +=      -DDEBUG
#DEFS           +=      -DULTRADEBUG
#DEFS            +=      -DONLYBIG
#DEFS            +=      -DNO_EXCLUSION
#DEFS		+=	-DNO_MASS_CONSERVATION
#DEFS		+=	-DRANKED
